### ISSUE TITLE
Site is not remembering additional selected columns

### ISSUE THREAD

**Issue by londonjob** [fossfox-com/fossfox#1]
Actual:
1) select additional columns (e.g. Founded and Offices)
2) Go to any other place in the application e.g https://fossfox.com/gradle
3) Return back home
4) additional selected columns are gone

Expected:
additional columns stay selected after returning home

**Comment by 4kimov** [comment]
Thank you, good feedback. Do you think this should only apply to homepage? (other types of pages have different columns enabled by default)

**Comment by londonjob** [comment]
I tried to find out what you meant with "other types of pages" but I failed to do so. Generally I would say when a user is for example interested in the type of "Employment" he wants to see this column everywhere once he additionally added it by himself.

**Comment by 4kimov** [comment]
Sorry, I should've elaborated, this is what I meant:

Tech page: https://fossfox.com/kubernetes
Dev page: https://fossfox.com/backend-engineer-jobs
etc

I agree, if a user has enabled a particular column, it should show up everywhere by default. Thanks for the feedback, I'll keep this issue open til it's implemented.

**Comment by 4kimov** [comment]
Done. Thank you for your feedback.
