### ISSUE TITLE
Adding the possibility to post a job using GUI

### ISSUE THREAD

**Issue by Dynnammo** [fossfox-com/fossfox#4]
**Context**
As a company HR recruiter, I would like to post offers on fossfox.com. I therefore click on "post jobs for free" on the top right, and am redirect to GitHub.

**Frustration**
As I'm not a developer myself, I may not have a GH account, and may not know how to create PRs, manipulate files etc.

**Solution**
Adding the possibility to create a job offer graphically. On the backend, it automatically creates PR with filled information using `foofox-com` GH token, and inform the user that its offer is currently analysed and will be reviewed soon.

**Side remarks**
As this project is very developer-centric, this feature might seem currently irrelevant.

**Comment by 4kimov** [comment]
Hi @Dynnammo, thank you very much for the feedback. This feature is very relevant and on our todo list. I'll keep this issue open until it's implemented & on production.

**Comment by 4kimov** [comment]
Hi @Dynnammo, [beta dashboard](https://dashboard.fossfox.com/) was pushed out recently, any chance you could try it out?

P.S: Short links had to be expanded because it's one of the ways our system tracks if the job page is still up and running.

**Comment by Dynnammo** [comment]
Good morning @4kimov !

Just tested right now, but captcha keeps failing :thinking: 
![image](https://github.com/fossfox-com/fossfox/assets/33259633/8a8f819f-0fa0-4621-a3fa-c285b3b3d084)

**Comment by 4kimov** [comment]
Hi @Dynnammo, thank you for the heads up and sorry for the troubles. Pushed an update, could you please try again?

**Comment by Dynnammo** [comment]
Just tested out, it works, just have to wait your review :smile: 
![image](https://github.com/fossfox-com/fossfox/assets/33259633/aa84f2be-5fc2-4fec-a4fd-7f960fe9ad71)

**Comment by 4kimov** [comment]
Great that you were able to proceed, thank you for giving it a second try! I've emailed you to continue this conversation outside of Github, so going to close this issue for now 🙏
